# Generated by Django 3.1 on 2020-09-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default=None, max_length=20, unique=True, verbose_name='username')),
                ('business_Name', models.CharField(default=None, max_length=20, null=True)),
                ('business_Email', models.EmailField(max_length=60, null=True)),
                ('business_Address', models.CharField(default=None, max_length=256, null=True)),
                ('business_Phone', models.CharField(default=None, max_length=15, null=True)),
                ('business_Number', models.CharField(default=None, max_length=20, null=True)),
                ('password', models.CharField(max_length=255, verbose_name='password')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='invoice_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default=None, null=True, upload_to='')),
                ('logoname', models.CharField(default=None, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last', models.CharField(max_length=20)),
            ],
        ),
    ]
