# Generated by Django 3.1 on 2020-09-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fillform', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_info',
        ),
    ]
