# Generated by Django 3.1 on 2020-09-08 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fillform', '0002_delete_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_detail',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
