# Generated by Django 3.1 on 2020-09-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillform', '0003_invoice_detail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_detail',
            name='logo',
            field=models.ImageField(default=None, null=True, upload_to='logos/'),
        ),
    ]
