# Generated by Django 3.1 on 2020-09-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillform', '0004_auto_20200908_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='logo',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='invoice_detail',
            name='logo',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
