# Generated by Django 3.1 on 2020-09-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillform', '0006_auto_20200909_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_detail',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='invoice_detail',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='invoice_detail',
            name='total',
        ),
        migrations.AddField(
            model_name='invoice_detail',
            name='amounts',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
