# Generated by Django 3.1 on 2020-09-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillform', '0007_auto_20200909_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_detail',
            name='table_Items',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_detail',
            name='terms',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
