version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/www/project
permissions:
  - object: /home/ubuntu/www
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 6000
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 6000
      runas: ubuntu