version: "3.3"
   
services:
  web:
    build: .
    command: sh -c "python3 manage.py collectstatic --noinput && python3 manage.py runserver 0.0.0.0:80"
    volumes:
      - .:/code
    ports:
      - "80:80"